* Papers Read

| Title | Author | Date | Pages | Read Date |
| Space and Time as Relations: The Theoretical Approach of Leibniz | Basil Evangelidis | 2 April 2018 | 15 | |

* [[https://res.mdpi.com/philosophies/philosophies-03-00009/article_deploy/philosophies-03-00009.pdf?filename=&attachment=1][Space and Time as Relations: The Theoretical Approach of Leibniz]]
Basil Evangelidis (2018)
15 pages

Leibniz believed that space and time are not real entities but virtual relationships and mathematical concepts. He was led to this conclusion through the problem of the relationship of the mind with space, the study of the nature of the continuous in various mathematical fields, and the observation of linear and centrifugal movement, as well as the confrontation with atomism based on the assumption of the inexistence of vacuum.

Space is an order of coexisting phenomena
Time is an order of successive phenomena

Simultaneity and Sequentiality.

Today we call this view Relationalism: spatial and temporal relationships between objects and events are immediate and not reducible to space-time point relations, and all movement is the relational movement of bodies. The controversy about the ontological status of space and time began with the distinction between primary and secondary qualities developed by Democritus, Galileo, Descartes, and Locke.

According to Descartes, primary qualities (e.g., height, width, depth) unlike secondary qualities (e.g., roughness, color), are perceptible with an accuracy that depends on the position of the observer to the physical objects. Primary properties reveal the true nature of the body. Through this distinction, Descartes output meanings, which Leibniz also analyzed. These were:
1) Observability
2) the Primary, true nature of the body, the object
3) Spatial dimensions, as physical characteristics of the physical object

From the above premises, Newton concluded that there is a similar distinction between sensible space and time, where the sensible secondary properties appear, and the completely differently theorized, mathematically defined space and time, where unseen masses and atoms of physics exist.

On the account of this distinction, Newton introduced the terms “absolute/relative, true/apparent, mathematical/common” in Principia: The Mathematical Principles of Natural Philosophy. Since we can imagine that extramundane space without bodies, as an extension, is independent of the bodies, then the space, according to Newton, is certainly not material, but has its own way of existence. Furthermore, absolute and relative motion can be identified by their properties, their causes, and their effects. The absolute acceleration developed during rotation that is observable by the diverting forces from its axis is the high spot of the Newtonian argument.

In summary, Newtonian science distinguished absolute from relative space and time. Absolute, genuine, and mathematical time, in itself, flows regularly due to its nature, without dependence on anything from the exterior. Its other name is continuity. Relative, apparent, and common time is a certain perceptible, external, detailed, and unstable measure of the duration of movement. Absolute space, due to its own nature, without dependence on any factor from the outside, always remains the same and motionless. Relative space is a certain mobile dimension or measure of absolute space.
The famous controversy between Leibniz and Newton was not direct, but was mediated by Clarke, an English theologian. The fields of dispute were meant to be observability, measurement, and experiment. The relational theory of Leibniz was articulated in juxtaposition to the theory of Newton. Leibniz believed that space is something completely relative. That is to say, space is the order of coexistence, as the time is an order of sequences.

Space implies, in terms of possibility, an order of things that exist at the same time, considered as if they existed together, without examining their form of existence. Space is nothing other than the order of existence of concurrent objects.

The frame of reference of space and time involves natural objects and their relations, events, and processes.

For relational theory, the possibility of a material universe as an ensemble that moves either in space or in time is without meaning, as space and time do not exist independently from the order of bodies and incidents in the Universe.

All relational theories for space-time attribute territorial, time, and space-time relations to material objects. Yet relations are not an absolute reality within the things, but a determination that thought, intellect, adds to things. All relations are ostensible, that is to say that they are well consolidated phenomena. Space-time relations are not ontologically prior to the relations between natural bodies.

** Innate Mathematical Concepts

According to Leibnizian relationalism, extension or space, surfaces, lines and points are nothing beyond rational entities, innate ideas, and relations of orders, namely orders of coexistence. Relational truths are based on incidents of a representational nature that take the form subject—predicate. The utmost indivisible units include all their predicates in such a way that the relations are ostensible and reducible to categorical constitutive parts, that is to say attributes.

The space, defined as a series of coexistence is not an empirical but a rational truth: it is a virtual entity. It belongs to a set of entities that are characterized by uniformity and contains no variety The concepts of space and time, as well as other entities of pure mathematics, are not generalizations extracted from raw empirical material. They are already in our minds, and emerge with experience.

The spatial extension is infinitely divisible and divided. Nevertheless, the true infinite, strictly speaking, is found only in the Absolute, while space is indefinitely extensive.

According to Leibniz, the moments and the points are not parts of time and space, but only terms. Simple terms referring to things come prior to the sums. The parts are real, defined, and prior in comparison to the whole; but in reference to the ideal entities, such as time and space, unity precedes, and the simple terms follow. The parts are only possible, indistinct, arbitrary divisions, following the whole.

Leibniz compared the number with extension and with mathematical bodies. Whereas numbers has no existence without the things measured, the extension and the mathematical bodies are meaningless without entities that act or bear, or without movement. Space, time, and infinity are not real sets; and therefore, we have no positive idea about them. Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time.

Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time. The mathematical entities are ideal, as for instance the “shape”, which is never exact and strictly specific in nature. It is not even a universally true and clear quality outside thought. The mathematical entities are modalities, undefined quantities, with which we can access the discrete quantities of the real world.

** 1.2 The Continuous

In contrast to Newton, who believed that each point-material object coincides with a point of substantial space, Leibniz treated points as extremities or modalities or modes. The location, without doubt, is nothing more than a way of something, like the former or the latter. A mathematical point itself is nothing but a way, namely an extremity. The extension derives from the position but adheres also continuity to the position. Points are positioned in place, but they neither sustain continuity, nor can they stand by themselves.

The ideal, virtual continua are inherent mathematical ideas and they are not composed of parts or points, nor of moments, because the perception of the moment does not contain a sequence. The continuum is everywhere dense, i.e., solid, homogeneous and ceaseless, a plenum, i.e., without breakage of continuity (uninterrupted.

For Leibniz, space is infinitely divisible — in the Aristotelian sense of possibility. Space and time are an order of potentialities. The spatial relationships, although they build up space, are antecedent and parasitic upon space. The Leibnizian space is not the simple sum of the ideal spatial relations but is prior to its parts and divisions.

Thus appears the unrelenting, the completeness of space, which is quondam, as it is not composed of extensional pieces of finite or infinite dimensional areas, separate from each other by two-dimensional boundaries, but is simply divisible, potentially divided. The apparent change and spatial extension are not authentically continuous, because their sequence is terminated. However, there are differences here: the spatial extension is a static representation, it lacks a privileged set of directions and forms a three-dimensional continuum. The apparent change is irreversible and therefore directional; it forms a linear or one-dimensional continuum.

** 1.3 The Time and the Monad

The Leibnizian theory of time is not articulated with completeness, though it is closely connected with the Monadology. In an earlier letter to Jacob Thomasius, Leibniz wrote that time is nothing else beyond measure of motion. Since each magnitude is a number that consists of parts, why should the definition of time by Aristotle, as a number of change surprise us?

Newton believed that a number of specific event concurrent with one another, they are simultaneous with a certain point in time. According to Leibniz, however, moments constitute only apparent change. A certain phenomenal duration is really dense or actually infinitely divisible, as the physical objects are. Nevertheless, time is uniform or homogeneous; we can divide it an infinite number of times, but it remains prior to its parts, due to the fact that it does not consists of them. It is an idealized entity that refers to the order of succession-relations in the changing phenomena, when we remove the peculiarities of their relata. The truths concerning the time structure are eternal and determine the changing of the phenomena. The fundamental law of being is temporality or succession. n empty space is something we can imagine, but a gap in time incomprehensible. Leibniz wrote to De Volder that time, in contrast to space, is included both in spiritual and in material things, and therefore in perception, the activity of the Monad.

** 2. The Monads

The philosophical stimulation for the writing of Monadology was the problem of the Cartesian mind-body dualism. Leibniz was impressed by the belief that the pineal gland was associated with the communication between cognition and extension, the search for continuity between soul and body. He also sought to quash the naturalistic theory of Locke, who considered space as the common basis of the interaction between mind and matter. Leibniz did not think “that substance is constituted by extension alone, since the concept of extension is incomplete. Nor do I think that extension can be conceived in itself, but I consider it an analyzable and relative concept, for it can be resolved into plurality, continuity, and coexistence or the existence of parts at the one and the same time”.

Leibniz formulated the Monadology gradually by taking the appropriate distances from Cartesianism. Regarding the substance in two of his early works he note: “1. Substance is being which subsists in itself; 2. Being which subsists in itself is that which has a principle of action within itself (…) no body is to be taken as substance, apart from a concurrent mind (…) Whatever is not substance is accident or appearance …”. In addition he wrote, “I call substance whatever moves or is moved”.

The monad is simple ,unified, indivisible, unborn, and imperishable. It is because it has no parts. The monads form compounds, composites, accumulations (aggregata) of simple things. They do not have an extension or form, and they are not visible. However, they are the real elements of natural things. Each unique substance expresses the whole universe in its own way and includes in its concept all events with all their circumstances and all the continuity of external things. The monads are endowed with perception and they are self-reactive. One monad can be distinguished from another by its perceptions, the representation of plurality in the simple, and appetitions, its tendencies, the striking from one perception to another. The nature of the monad is the representation. A monad represents the entire universe, but more distinctly it represents the body that constitutes its entelechy.
The primary feature of the monads, their primary power is perception. Perception is a certain conjunction of the simple with the multiple; it is also the distinction, the identification and the selection, it is the creation and the harmony. The monad as ultimum subsistens is the ultimate basis of all properties and determinations, as ultimum perdurabile is the foundation of any change and as vis activa  itself the source of activity. Pure percpetions concern active states of the active primitive force, in other words the first entelechy which is the soul of living beings. All simple substances or created monads are entelechies of bodies. The composition of the monadic entelechies gives the substantial form to the inorganic world, the principle of impetus. The unclear percpetions relate to potential situations of the passive primitive force (materia prima), derived from the spontaneity of the monad. Apart from the primary forces, there also exist derived ones: by the aggregation of materia prima, secondary matter is being produced, which is governed by active forces as the vis viva, namely the kinetic energy, and the conatus, expressing the potential speed. The second material however is governed by passive forces as well: inertia and antitypia, namely impenetrability, which will be analyzed by the physical theory of Leibniz.

*** 2.1 The Immutable World of Monads Is Not in Space-Time

The spatial extension belongs to the domain of phenomena, while the monads are not placed in space; they only represent each other with spatiotemporal characteristics. A representation of a monad of the real world of representational monads is a real condition of the monad, which along with coexisting monads — which are found in suitable corresponding situations — formulate the real world of the monads. A monad beholds the world of phenomena as if it were, in itself, in the center of this vision.

All substances are active. Space and time are produced by the monads and their primary characteristics, their properties. In concert with the principle of perfection and with its equivalent principle of the predetermined harmony, Leibniz concluded that space is a relation inherent in the cross-sectional situations, i.e., the perceptions of monads, whereas the mutual agreement of the monads is such that every perception of a given unit corresponds precisely to a perception of any other unit. The power or activity, and not the extension or passive receptivity, is the deterministic property of the reality.

A possible interpretation of the Leibnizian theory may be closer to the Kantian philosophy: space and time do not exist as completely independent instances or continua, but they make sense noly in the subjectively generated contents of the observer’s consciousness. The monad is this energetic observer, who after all lacks any windows; the monad is not located in space. However, it knows the space because it possesses the ability to perceive both the innate, necessary, tautological truths of reason, and the contingent truths of empirical facts.

*** The Monadic Change and the Mathematical Concept of Series

