* Papers Read

| Title | Author | Date | Pages | Read Date |
| Space and Time as Relations: The Theoretical Approach of Leibniz | Basil Evangelidis | 2 April 2018 | 15 | |

* [[https://res.mdpi.com/philosophies/philosophies-03-00009/article_deploy/philosophies-03-00009.pdf?filename=&attachment=1][Space and Time as Relations: The Theoretical Approach of Leibniz]]
Basil Evangelidis (2018)
15 pages

Leibniz believed that space and time are not real entities but virtual relationships and mathematical concepts. He was led to this conclusion through the problem of the relationship of the mind with space, the study of the nature of the continuous in various mathematical fields, and the observation of linear and centrifugal movement, as well as the confrontation with atomism based on the assumption of the inexistence of vacuum.

Space is an order of coexisting phenomena
Time is an order of successive phenomena

Simultaneity and Sequentiality.

Today we call this view Relationalism: spatial and temporal relationships between objects and events are immediate and not reducible to space-time point relations, and all movement is the relational movement of bodies. The controversy about the ontological status of space and time began with the distinction between primary and secondary qualities developed by Democritus, Galileo, Descartes, and Locke.

According to Descartes, primary qualities (e.g., height, width, depth) unlike secondary qualities (e.g., roughness, color), are perceptible with an accuracy that depends on the position of the observer to the physical objects. Primary properties reveal the true nature of the body. Through this distinction, Descartes output meanings, which Leibniz also analyzed. These were:
1) Observability
2) the Primary, true nature of the body, the object
3) Spatial dimensions, as physical characteristics of the physical object

From the above premises, Newton concluded that there is a similar distinction between sensible space and time, where the sensible secondary properties appear, and the completely differently theorized, mathematically defined space and time, where unseen masses and atoms of physics exist.

On the account of this distinction, Newton introduced the terms “absolute/relative, true/apparent, mathematical/common” in Principia: The Mathematical Principles of Natural Philosophy. Since we can imagine that extramundane space without bodies, as an extension, is independent of the bodies, then the space, according to Newton, is certainly not material, but has its own way of existence. Furthermore, absolute and relative motion can be identified by their properties, their causes, and their effects. The absolute acceleration developed during rotation that is observable by the diverting forces from its axis is the high spot of the Newtonian argument.

In summary, Newtonian science distinguished absolute from relative space and time. Absolute, genuine, and mathematical time, in itself, flows regularly due to its nature, without dependence on anything from the exterior. Its other name is continuity. Relative, apparent, and common time is a certain perceptible, external, detailed, and unstable measure of the duration of movement. Absolute space, due to its own nature, without dependence on any factor from the outside, always remains the same and motionless. Relative space is a certain mobile dimension or measure of absolute space.
The famous controversy between Leibniz and Newton was not direct, but was mediated by Clarke, an English theologian. The fields of dispute were meant to be observability, measurement, and experiment. The relational theory of Leibniz was articulated in juxtaposition to the theory of Newton. Leibniz believed that space is something completely relative. That is to say, space is the order of coexistence, as the time is an order of sequences.

Space implies, in terms of possibility, an order of things that exist at the same time, considered as if they existed together, without examining their form of existence. Space is nothing other than the order of existence of concurrent objects.

The frame of reference of space and time involves natural objects and their relations, events, and processes.

For relational theory, the possibility of a material universe as an ensemble that moves either in space or in time is without meaning, as space and time do not exist independently from the order of bodies and incidents in the Universe.

All relational theories for space-time attribute territorial, time, and space-time relations to material objects. Yet relations are not an absolute reality within the things, but a determination that thought, intellect, adds to things. All relations are ostensible, that is to say that they are well consolidated phenomena. Space-time relations are not ontologically prior to the relations between natural bodies.

** Innate Mathematical Concepts

According to Leibnizian relationalism, extension or space, surfaces, lines and points are nothing beyond rational entities, innate ideas, and relations of orders, namely orders of coexistence. Relational truths are based on incidents of a representational nature that take the form subject—predicate. The utmost indivisible units include all their predicates in such a way that the relations are ostensible and reducible to categorical constitutive parts, that is to say attributes.

The space, defined as a series of coexistence is not an empirical but a rational truth: it is a virtual entity. It belongs to a set of entities that are characterized by uniformity and contains no variety The concepts of space and time, as well as other entities of pure mathematics, are not generalizations extracted from raw empirical material. They are already in our minds, and emerge with experience.

The spatial extension is infinitely divisible and divided. Nevertheless, the true infinite, strictly speaking, is found only in the Absolute, while space is indefinitely extensive.

According to Leibniz, the moments and the points are not parts of time and space, but only terms. Simple terms referring to things come prior to the sums. The parts are real, defined, and prior in comparison to the whole; but in reference to the ideal entities, such as time and space, unity precedes, and the simple terms follow. The parts are only possible, indistinct, arbitrary divisions, following the whole.

Leibniz compared the number with extension and with mathematical bodies. Whereas numbers has no existence without the things measured, the extension and the mathematical bodies are meaningless without entities that act or bear, or without movement. Space, time, and infinity are not real sets; and therefore, we have no positive idea about them. Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time.

Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time. The mathematical entities are ideal, as for instance the “shape”, which is never exact and strictly specific in nature. It is not even a universally true and clear quality outside thought. The mathematical entities are modalities, undefined quantities, with which we can access the discrete quantities of the real world.

** 1.2 The Continuous

In contrast to Newton, who believed that each point-material object coincides with a point of substantial space, Leibniz treated points as extremities or modalities or modes. The location, without doubt, is nothing more than a way of something, like the former or the latter. A mathematical point itself is nothing but a way, namely an extremity. The extension derives from the position but adheres also continuity to the position. Points are positioned in place, but they neither sustain continuity, nor can they stand by themselves.

The ideal, virtual continua are inherent mathematical ideas and they are not composed of parts or points, nor of moments, because the perception of the moment does not contain a sequence. The continuum is everywhere dense, i.e., solid, homogeneous and ceaseless, a plenum, i.e., without breakage of continuity (uninterrupted.

For Leibniz, space is infinitely divisible — in the Aristotelian sense of possibility. Space and time are an order of potentialities. The spatial relationships, although they build up space, are antecedent and parasitic upon space. The Leibnizian space is not the simple sum of the ideal spatial relations but is prior to its parts and divisions.

Thus appears the unrelenting, the completeness of space, which is quondam, as it is not composed of extensional pieces of finite or infinite dimensional areas, separate from each other by two-dimensional boundaries, but is simply divisible, potentially divided. The apparent change and spatial extension are not authentically continuous, because their sequence is terminated. However, there are differences here: the spatial extension is a static representation, it lacks a privileged set of directions and forms a three-dimensional continuum. The apparent change is irreversible and therefore directional; it forms a linear or one-dimensional continuum.

** 1.3 The Time and the Monad

The Leibnizian theory of time is not articulated with completeness, though it is closely connected with the Monadology. In an earlier letter to Jacob Thomasius, Leibniz wrote that time is nothing else beyond measure of motion. Since each magnitude is a number that consists of parts, why should the definition of time by Aristotle, as a number of change surprise us?

Newton believed that a number of specific event concurrent with one another, they are simultaneous with a certain point in time. According to Leibniz, however, moments constitute only apparent change. A certain phenomenal duration is really dense or actually infinitely divisible, as the physical objects are. Nevertheless, time is uniform or homogeneous; we can divide it an infinite number of times, but it remains prior to its parts, due to the fact that it does not consists of them. It is an idealized entity that refers to the order of succession-relations in the changing phenomena, when we remove the peculiarities of their relata. The truths concerning the time structure are eternal and determine the changing of the phenomena. The fundamental law of being is temporality or succession. n empty space is something we can imagine, but a gap in time incomprehensible. Leibniz wrote to De Volder that time, in contrast to space, is included both in spiritual and in material things, and therefore in perception, the activity of the Monad.

** 2. The Monads

The philosophical stimulation for the writing of Monadology was the problem of the Cartesian mind-body dualism. Leibniz was impressed by the belief that the pineal gland was associated with the communication between cognition and extension, the search for continuity between soul and body. He also sought to quash the naturalistic theory of Locke, who considered space as the common basis of the interaction between mind and matter. Leibniz did not think “that substance is constituted by extension alone, since the concept of extension is incomplete. Nor do I think that extension can be conceived in itself, but I consider it an analyzable and relative concept, for it can be resolved into plurality, continuity, and coexistence or the existence of parts at the one and the same time”.

Leibniz formulated the Monadology gradually by taking the appropriate distances from Cartesianism. Regarding the substance in two of his early works he note: “1. Substance is being which subsists in itself; 2. Being which subsists in itself is that which has a principle of action within itself (…) no body is to be taken as substance, apart from a concurrent mind (…) Whatever is not substance is accident or appearance …”. In addition he wrote, “I call substance whatever moves or is moved”.

The monad is simple ,unified, indivisible, unborn, and imperishable. It is because it has no parts. The monads form compounds, composites, accumulations (aggregata) of simple things. They do not have an extension or form, and they are not visible. However, they are the real elements of natural things. Each unique substance expresses the whole universe in its own way and includes in its concept all events with all their circumstances and all the continuity of external things. The monads are endowed with perception and they are self-reactive. One monad can be distinguished from another by its perceptions, the representation of plurality in the simple, and appetitions, its tendencies, the striking from one perception to another. The nature of the monad is the representation. A monad represents the entire universe, but more distinctly it represents the body that constitutes its entelechy.
The primary feature of the monads, their primary power is perception. Perception is a certain conjunction of the simple with the multiple; it is also the distinction, the identification and the selection, it is the creation and the harmony. The monad as ultimum subsistens is the ultimate basis of all properties and determinations, as ultimum perdurabile is the foundation of any change and as vis activa  itself the source of activity. Pure percpetions concern active states of the active primitive force, in other words the first entelechy which is the soul of living beings. All simple substances or created monads are entelechies of bodies. The composition of the monadic entelechies gives the substantial form to the inorganic world, the principle of impetus. The unclear percpetions relate to potential situations of the passive primitive force (materia prima), derived from the spontaneity of the monad. Apart from the primary forces, there also exist derived ones: by the aggregation of materia prima, secondary matter is being produced, which is governed by active forces as the vis viva, namely the kinetic energy, and the conatus, expressing the potential speed. The second material however is governed by passive forces as well: inertia and antitypia, namely impenetrability, which will be analyzed by the physical theory of Leibniz.

** 2.1 The Immutable World of Monads Is Not in Space-Time

The spatial extension belongs to the domain of phenomena, while the monads are not placed in space; they only represent each other with spatiotemporal characteristics. A representation of a monad of the real world of representational monads is a real condition of the monad, which along with coexisting monads — which are found in suitable corresponding situations — formulate the real world of the monads. A monad beholds the world of phenomena as if it were, in itself, in the center of this vision.

All substances are active. Space and time are produced by the monads and their primary characteristics, their properties. In concert with the principle of perfection and with its equivalent principle of the predetermined harmony, Leibniz concluded that space is a relation inherent in the cross-sectional situations, i.e., the perceptions of monads, whereas the mutual agreement of the monads is such that every perception of a given unit corresponds precisely to a perception of any other unit. The power or activity, and not the extension or passive receptivity, is the deterministic property of the reality.

A possible interpretation of the Leibnizian theory may be closer to the Kantian philosophy: space and time do not exist as completely independent instances or continua, but they make sense only in the subjectively generated contents of the observer’s consciousness. The monad is this energetic observer, who after all lacks any windows; the monad is not located in space. However, it knows the space because it possesses the ability to perceive both the innate, necessary, tautological truths of reason, and the contingent truths of empirical facts.

** 2.2 The Monadic Change and the Mathematical Concept of Series

The Leibnizian philosophy of science is divided into 3 levels, the metaphysical, the conceptual (of the mathematical entities), and the apparent (the bodies). The metaphysical is the level of the mind. The monad or the mind does not accept influences but only affects the body and its representations. The idealizations of space and time are, as we have seen, orders of coexistence or succession. The concept of order originates from the ideal level, while the concepts of succession and coexistence reflect the phenomena. The monads are prerequisites and foundations of the phenomena, they dispose neither a gradual onset, nor a gradual ending, but an abrupt onset and abrupt end. Leibniz describes the monad as a focus of perception, of an anterograde situation that surrounds and represents the multiplicity within unity. The monadic reality is changing entirely, moving from one state another. This real change is a prerequisite for the good consolidation of apparent change. the monadic alteration is not just a virtual thing or an apparent time-like order, but a real time-like order.

“There is, moreover, a definite order in the transition of our perceptions when we pas from one to the other through intervening ones. This order, too, we can call a path. But since it can vary in infinite ways, we must necessarily conceive of one that is most simple, in which the order of proceeding through determinate intermediate states follows from the nature of the thing itself, that is, the intermediate stages are related in the simplest way to both extremes”.

This change in the order of percpetions appears to have a distinct and discontinuous nature: each present state of a substance is a consequence of its previous situation. Clearly, the changes are not truly continuous, there appear interruptions, ruptures of continuity. However, they are characterized by density, because the dense causal connections at the level of phenomena must be correct representations of dense causal connections, with dynamic form. Other times the change is characterized as continuous and flows in conformity with an internal principle. The action of the internal principle that brings about the passage from one perception to another is called appetition.

Two substances are never completely identical to each other: each monad is different from others like a circle is different from an ellipse is different from a parabola. One may consider them as conic sections obtained in accordance with the law of continuity through infinitely small subtle shifts. The essence of the monad is beyond finite analysis and one can access it only through the law of individual series. The procured force is the situation at present, in its trend towards a next state, or the prior implication of the next state. Meanwhile, the primary force exists implying everything that will happen, that is, the nature of the primary active force consists in a law of duration of a progressive series that persists with no obstacle. The procured force is a term of the series, while the active force is the law of the series.

The problems of perception are translatable into terms of geometry, different analysis, perspective, minimum perceptions etc. The complicated and infinitesimal movements of substances are represented by extreme curves of curves, namely by geometric models which mount the vibration of the monad with its maximum and minimum curve. The curve of the maxima is always increasing, and the curve of the minima always decreases. Progression emerges when the increase is greater than the decrease. The order is more fundamental than the disorder, as the real against the phenomenon. It is impossible to find in space the ultimate privileged spot from where one can approach the universal harmony. The sum is privileged and non-privileged from the viewpoint of the fixed stars. In an equivalent way, there is no privileged point of time.

Leibniz proposed a new mathematical model inspired by the theory of the infinite series. However, although aware of the distinction between convergent and divergent series, he did not propose a criterion for their distinction. Anyway, he tended to choose the most perfect series. In terms of combinatorics the “richest” series is one that involves differences and reversals. There is a class of negative or reciprocating type, for the one, the unity: without parts, without form, without division. It does not involve death, initiation, change. There is a progressive class with clearly aggregative characteristics for the multiple: parts, shape, division, dissolution, destruction, beginning, creation, increase, decrease, every form of influence. These reverse features of the one and the multiple are not expressed in accordance with an arbitrary order, but follow the development of two laws, of composition and analysis: they are synthesized by external parts, which directly unfold into the elemental world of geometry and mechanics, attributing the onset of motion in a naturalistic way. The latter two classes are sequences of positive or negative geometrical and mechanical propositions, which order the sum of the terms. They are also sequences of negative or positive propositions of a new set of terms, established by the primary relationship of the analysis of the parts, i.e., of the access of dividing up the indivisible, the atom or the element; of dissolution of heaps of cohesion, resistance, impermeability; of destruction and passing to complexity; and of change, reduction, and attenuation, i.e., intersection of some part of a compound.

** 3. Space, Time, and Motion in the Physical Theory of Leibniz

Descartes believed that the essence of things is the extension which they occupy in space. He reduced all the characteristics of the bodies in modes of extension, supposing that physical changes are movements in space. Leibniz, after 1676, when he turned more clearly against Cartesianism, was confident that the data we observe are limited to material things, their properties, and relations. The Leibnizian Relationalism is based on two key aspects: 1) space-time is not a substance, namely there is no substratum of spatial, temporal, and spatiotemporal points, endowed with spatiotemporal relations ontologically prior to the spatiotemporal relationship between physical objects and events; and 2) the motion is relative, and all spatiotemporal relations are arranged between physical objects and events.

On the contrary, Newton, while accepting that many relationships have no observational consequences, showed that the absolute acceleration of a physical object that rotates is itself observable. To depict the forces generated by the circular motion, he used two mental experiments: the centrifugal forces on the surface of the water in a rotating bucket, and the tension of a string joining two spheres rotating about their center of mass. According to these representations, linear accelerations create observable forces. Newton attributed these absolute accelerations and generated forces to absolute space, which is an unchanging reference system. Therefore, the Newtonian science considered as absolute the differences between state of rest, uniform motion, and accelerated motion. Samuel Clarke, in his renowned correspondence with Leibniz, pinpointed the importance of absolute acceleration.

If the movement of the water in the thought experiment was only relative, yaw forces from the rotation axis would be zero. Leibniz however refused to accept absolute acceleration, although he claimed that we must distinguish between “mere relative change” and “absolute true motions of a body”. Leibniz made this distinction only with respect to the cause of movement: In each movement of two material objects, the body that really moves is the cause of the change in itself.

This is not the absolute motion of Newton, but true motion relative to another body. Leibniz characterized the true motion as a subcase of relative motion: the actual motion is relative movement whose cause is the body that really moves. He believed that the centrifugal and centripetal movement are examples of dead forces (potentia motruus) that are infinitely weaker than the living force. What was, according to Leibniz, real and absolute in motion was the driving force, a tendency to move that consists in vis viva, a real and substantial entity, a fundamental absolute quantity which is inherent in substances.

* Leibniz on Pre-established Harmony and Causality
Jeffrey K. McDonough

There are two realms: one of bodies and efficient causation, one of minds and final causation.

** A Pre-established Harmony: Bodies and Minds

How is it that our minds and bodies can causally effect each other? Leibniz’s novel solution to this mind-body problem is that they can’. The interaction between our minds and bodies that seems so obvious to us is, in reality, an illusion, although “well-founded.”

At just the moment that one forms an intention to move their leg, their leg moves of its own accord. At just the moment that the ball collides with one’s hand, the mind independently comes to experience pain. Leibniz suggests taht mind and body are like two causally independent but synchronized clocks: the appearance of causal interaction between them is an illusion founded on a harmony pre-established by God.

Leibniz’s theory of pre-established harmony feels a bit like Indra’s Pearls where every mind has mutual perception and the whole consists of such mutual perceptions. Drawing on theoretical considerations, Leibniz insists that each mind perceives everything that happens in its world, that is not only in its immediate vicinity, but also across the city, on the other side of the earth, and indeed, on the other side of the universe.

Every body is connected and when a change happens in any body anywhere, a corresponding change occurs in a mind. When a change happens in any mind with a corresponding change in its body, ripple-effects occur in every other existing body.

Leibniz’s theory of pre-established harmony thus ultimately demands not merely the divine coordination of particular mind-body pairs, but even more boldly the divine coordination of each mind with all existing bodies and each body with all existing minds.

Leibniz defends his theory of pre-established harmony by highlighting that it helps to reconcile the metaphysics of Aristotelian-Scholasticism with mechanistic science. Leibniz also, I feel arrived at this theory by examining each of the existing alternatives of the time.

An alternative theory is the theory of physical influx. It posits, as Leibniz understands it, that minds and bodies causalyl interact when something – some form of being — passes from one substance to the other. Although they were often vague on this point, Leibniz’s suggestion that it is baseless.

Definition of this concept from Francisco Suárez, 17th century Scholastic, as per McDonough suggests that genuine causation occurs when a cause transfers some form of being to its effect. It implies that the foot causes the soccer ball to move by transferring something to the soccer ball — perhaps motion or energy — and that a picture of, say, Pelé causes the mental representation of Pelé by transferring something of Pelé image or likeness, first to a medium, then to the sensory organs, and ultimately to the mind.

Leibniz rejects the theory of physical influx as a general theory of causation because he thinks it is simply inconceivable that anything can be transferred from one substance to another.

Leibniz famously argued that monads are windowless: they don’t have any openings to enter through or go out of. If that is taken as axiomatic, then clearly causal interacitons between minds and bodies (or minds and minds) cannot be understood in terms of the theory of physical influx. For if nothing can go in or out of minds, hen they can neither receive from, no impart to, anything, including forms of being, as the theory of physical influx demands.

A second alternative to Leibniz’s theory of pre-established harmony is the theory of occasionalism. The theory had already enjoyed a long history before Leibniz’s time. It found new impetus, however, in suggestive remarks made by Descartes and was developed in vairous ways by second generation Cartesians such as Géraude de Cordemoy, Louis de la Forge, Arnold Geulincx, Johannes Clauberg, and above all, Nicholas Malebranche. The central idea of occasionalism is that God is the only genuine, efficacious cause in the world. Creatures lack any causal efficacy of their own and serve merely as occasions for God’s direct causal intervention.

Although, not popular today, the theory of occasionalism attracted a considerable following in Leibniz’s era and was supported by a raft of formidable arguments some of which continue to motivate some contemporary views on causation.

Leibniz rejects occasionalism for a variety of reasons. According to Leibniz, it is essential to created substances to be loci of causal activity. To suppose that creatures enjoy no causal efficacy of their own would be to reduce them to mere models of God. To Leibniz’s way of thinking, occasionalism thus collapses into the doctrines of Spinoza. Another line of argument draws on Leibniz’s understanding of God’s perfection. Leibniz maintains that his theory of pre-established harmony, according to which Godś design is so perfect that it requires no subsequent corrective intervention, is more suitable to God’s perfection than it is the theory of occasionalism, which would require God to constantly tinker with his creation.

In presenting his theory of pre-established harmony, Leibniz often speaks of there being two realms, a realm of bodies and efficient causation on the one hand, and a realm of souls and final causation on the other.

Material world is affected by efficient causes, whereas the world of souls are affected by the law of appetites or the final causes.

Minds unfold teleologically, that is, they act for the sake of ends. Bodies unfold efficiently, that is, they are driven along by efficient causes in accordance with the laws of nature.

** Causation in the Realm of Bodies

Leibniz contributed to formulating and refining laws of motion. He criticized Descartes’ laws of collision. He vigorously defends a series of conservation laws, including, most faously, the conservation of vis viva. Leibniz seeks to clarify what he sees as the philosophical implications of the laws of nature, defending, in particular, three central theses.

The first thesis concerns modal status of the laws of nature. Are laws such as Galileo’s law of falling bodies necessary or contingent? Descartes’s hugely influential treatement of the laws of motion implied to many that the laws of nature must be necessary — a view defended explicitly half-generation later by Spinoza. One such a view, the laws must be as they are. Galileo’s law of falling bodies could no more fail to hold tahn could the laws of geometry or arithmetic. Another view, attributed by Leibniz to Bayle, and dominant today, is that the laws of nature are contingent and arbitrary. On such a view, Galileo’s law just happens to be true. The world could have been different with respect to falling bodies: instead of falling with constant acceleration, bodies might have fallen with constant velocity or variable acceleration. Furthermore, on this view, there is no decisive reason in favour of Galileo’s law. If we imagine that God has created the world, we may imagine him as being indifferent, or at least not set upon, creating the world in accordance with Galileo’s law.

Leibniz opposes both of these extreme views. He maintains that the law of nature as neither necessary nor arbitrary. Rather they are contingent but nonetheless determined by considerations of optimality.

Leibniz effectively suggests that both Descartes and Bayle are wrong. Descartes is wrong because there is a sense in which the laws of nature are contingent. If we abstarct from God’s goodness, we can imagine God’s creating the world with different laws. In this respect, the laws of nature are not like the laws of arithmetic and geometry. But Bayle  —  at least as Leibniz interprets him  — is also wrong. Although the laws of nature are contingent, they are not arbitrary. God, according to Leibniz, has chosen to instantiate the actual laws of nature not out of whim or fancy, but because they are essential to the best of all possible worlds.

Leibniz’s second thesis concerns with what we might think of as the metaphysics of the laws of natrue. What are the laws of nature and how do they govern the world? Talk of the laws of nature, their creation, their discovery, etc. can encourage the thought that laws of nature are thing-like, that they are independent ingredients in the world on a par with mind and bodies. But that cannot be Leibniz’s picture. Leibniz’s fundamental ontology of the created world is exhausted by substances: true unities modeled on minds or organisims. Not being true unities — being nothing like minds or organisms  —  laws of nature cannot be counted among the fundamental ingredients of the created world. Rather, for Leibniz, they must be identified with concepts or abstractions enjoyed by rational minds and applicable to events in the world. Galileo’s law of falling bodies is not a thing but rather a pattern, a regularity or rule understood by God and other intelligent minds. With the laws of nature so understood, it is also immediately clear that, for Leibniz, the laws of nature cannot govern bodies by, say, pushing or pulling them around. Instead, Leibniz maintains that bodies are determined in their behaviour by forces within bodies themselves. Heavy bodies near the surface of the earth fall with a constant acceleration not because the laws of nature push or pull them, but rather because they have been endowed with intrinsic powers that direct them to fall with constant acceleration. For Leibniz, laws of nature are explanatorily powerful insofar as they allow us to subsume particular phenomena under general regularities, but they are not causally powerful in the sense that they directly bring about the behaviours they subsume.

Malebranche identifies the laws of nature with divine decrees. But how are those decrees supposed to regulate the behaviour of bodies?  Leibniz argues that if the laws of nature are identified with general decrees made at the beginning of creation, but not grounded in the intrinsic powers of bodies, then they cannot now be effective as there needs to be a force that still subsists with them. But might not the laws of nature be identified with general decrees and their efficacy nonetheless be grounded in God’s particular volitions, volitions made in accordance with those general decrees? Leibniz thinks this woudl be no better. For he insists that miracles occur when something happens that passes the forces of creatures (?) as would happen for example, if water were to burn or pigs were to fly. Given such an understanding of miracles, Leibniz argues that if the efficacy of the laws of nature were grounded in God’s particular volitions, then God would be committed to incessantly peforming miracles. Seeing such activity as being unworthy of God’s wisdom, Leibniz concludes that occasionalists fail to offer a tenable view of the nature and efficacy of the laws of nature.

Leibniz’s third central thesis concerns the role of teleological explanations in the natural science. Descartes and Spinoza made no appeals to final causes in physics. Spinoza seemed to go a step further in suggesting that teleological explanations get the order of explanation the wrong way around and the final causes are “nothing but human fictions”. While acknowledging the limits of earlier scholastic explanations, Leibniz nonetheless argues that a wholesale rejection of teleological explanation is neither necessary nor prudent. Like many proponents of the new science, Leibniz is happy to grant that we cannot hope to know all of God’s ends, but he sees no reason to suppose that we cannot discern some of them.

Leibniz’s work on the laws of optics provides him with another, less obvious, route for defending teleological explanations. Aroundd the late 1670’s, Leibniz came to see that the law of reflection could be derived from a principle acccording to which, as he puts it, “nature, proposing some end to itself, chooses the optimal means”.

By the early 1680s, Leibniz was able to provide a unified account of the two central laws of geometrical optics — the law of reflection and the law of refraction — by showing how both follow from the principle that light always travels along “easiest paths,” where easiest paths are rigorously defined in terms of distance and the resistances of the relevant medium. Leibniz continued to develop his approach to the laws of optics over the decades that followed, showing, for example, in his Tentamen Anagogicum of 1696 how optimal paths could also be determined in more difficult cases involving concave and convex mirrors. In a series of pioneering studies, Leibniz showed how similar reasoning could also be applied to solve specific problems in mechanics. The techniques that Leibniz pioneered in his optical and mechanical studies proved to be precursor to what are now known as variational principles.

Leibniz suggests that what we may call his “optimality principles” support teleological explanations within the natural world in two rather different ways. First, Leibniz thinks that optimality principles — like elegant laws of motion and simple conservation principles — support teleological arguments from design.

** 3. Causation in the Realm of Minds

Leibniz in his most mature peried thinks that the causal activity of creatures is ultimately grounded not in bodies but in monads alone.
