* Papers Read

| Title | Author | Date | Pages | Read Date |
| Space and Time as Relations: The Theoretical Approach of Leibniz | Basil Evangelidis | 2 April 2018 | 15 | 2 January 2022 |
| [[#leibniz-on-pre-established-harmony-and-causality][Leibniz on Pre-established Harmony and Causality]] | Jeffrey K. Mconough | 2017 | 20 | 19 December 2021 |
| [[#the-role-of-leibniz-and-haldane-in-weiners-cybernetics][The Role of Leibniz and Haldane in Weiners Cybernetics]] | George Gale | 1997 | 16 | 16 January 2021 |
| [[#leibniz-and-some-aspects-of-field-dynamics][Leibniz and Some Aspects of Field Dynamics]] | George Gale | | 20 | 6 Apr 2022 |
| [[#a-leibnizian-theory-of-concepts][A (Leibnizian) Theory of Concepts]] | Edward Zalta | | 29 | 28 Apr 2022 |
| [[#aristotle-the-scale-of-nature-and-modern-attitudes-to-animals][Aristotle, The Scale of Nature, and Modern Attitudes to Animals]] | Juliet Clutton-Brock | 1995 | 20 |  3 June 2023 |

* [[https://res.mdpi.com/philosophies/philosophies-03-00009/article_deploy/philosophies-03-00009.pdf?filename=&attachment=1][Space and Time as Relations: The Theoretical Approach of Leibniz]]
Basil Evangelidis (2018)
15 pages

Article on how Leibniz foresaw relativity, throw his critique of contemporary mechanistic philosophy.

Leibniz believed that space and time are not real entities but virtual relationships and mathematical concepts. He was led to this conclusion through the problem of the relationship of the mind with space, the study of the nature of the continuous in various mathematical fields, and the observation of linear and centrifugal movement, as well as the confrontation with atomism based on the assumption of the inexistence of vacuum.

Space is an order of coexisting phenomena
Time is an order of successive phenomena

Simultaneity and Sequentiality.

Today we call this view Relationalism: spatial and temporal relationships between objects and events are immediate and not reducible to space-time point relations, and all movement is the relational movement of bodies. The controversy about the ontological status of space and time began with the distinction between primary and secondary qualities developed by Democritus, Galileo, Descartes, and Locke.

According to Descartes, primary qualities (e.g., height, width, depth) unlike secondary qualities (e.g., roughness, color), are perceptible with an accuracy that depends on the position of the observer to the physical objects. Primary properties reveal the true nature of the body. Through this distinction, Descartes output meanings, which Leibniz also analyzed. These were:
1) Observability
2) the Primary, true nature of the body, the object
3) Spatial dimensions, as physical characteristics of the physical object

From the above premises, Newton concluded that there is a similar distinction between sensible space and time, where the sensible secondary properties appear, and the completely differently theorized, mathematically defined space and time, where unseen masses and atoms of physics exist.

On the account of this distinction, Newton introduced the terms:

- absolute/relative
- true/apparent
- mathematical/common

 in Principia: The Mathematical Principles of Natural Philosophy. Since we can imagine that extramundane space without bodies, as an extension, is independent of the bodies, then the space, according to Newton, is certainly not material, but has its own way of existence. Furthermore, absolute and relative motion can be identified by their properties, their causes, and their effects. The absolute acceleration developed during rotation that is observable by the diverting forces from its axis is the high spot of the Newtonian argument.

In summary, Newtonian science distinguished absolute from relative space and time. Absolute, genuine, and mathematical time, in itself, flows regularly due to its nature, without dependence on anything from the exterior. Its other name is continuity. Relative, apparent, and common time is a certain perceptible, external, detailed, and unstable measure of the duration of movement. Absolute space, due to its own nature, without dependence on any factor from the outside, always remains the same and motionless. Relative space is a certain mobile dimension or measure of absolute space.

The famous controversy between Leibniz and Newton was not direct, but was mediated by Clarke, an English theologian. The fields of dispute were meant to be observability, measurement, and experiment. The relational theory of Leibniz was articulated in juxtaposition to the theory of Newton. Leibniz believed that space is something completely relative. That is to say, space is the order of coexistence, as the time is an order of sequences.

Space implies, in terms of possibility, an order of things that exist at the same time, considered as if they existed together, without examining their form of existence. Space is nothing other than the order of existence of concurrent objects.

The frame of reference of space and time involves natural objects and their relations, events, and processes.

For relational theory, the possibility of a material universe as an ensemble that moves either in space or in time is without meaning, as space and time do not exist independently from the order of bodies and incidents in the Universe.

All relational theories for space-time attribute territorial, time, and space-time relations to material objects. Yet relations are not an absolute reality within the things, but a determination that thought, intellect, adds to things. All relations are ostensible, that is to say that they are well consolidated phenomena. Space-time relations are not ontologically prior to the relations between natural bodies.

** Innate Mathematical Concepts

According to Leibnizian relationalism, extension or space, surfaces, lines and points are nothing beyond rational entities, innate ideas, and relations of orders, namely orders of coexistence. Relational truths are based on incidents of a representational nature that take the form subject—predicate. The utmost indivisible units include all their predicates in such a way that the relations are ostensible and reducible to categorical constitutive parts, that is to say attributes.

TO PONDER: I am thinking that if predicates inhere in the subject, then they will have the structure of an unfolding tree, like in the tree of being. So in some sense, this is like the lattice getting reduced into a singular meaning or a certain projection of the multiway partition encompassed by it. Is there a structural way in which I can situate this insight? or is it the case that even if the predicate inheres in the subject, multiway unfoldings are possible and the resulting structure will be a partial order / a lattice?

The space, defined as a series of coexistence is not an empirical but a rational truth: it is a virtual entity. It belongs to a set of entities that are characterized by uniformity and contains no variety The concepts of space and time, as well as other entities of pure mathematics, are not generalizations extracted from raw empirical material. They are already in our minds, and emerge with experience. Space is a concept which belongs to the set of innate ideas that are objects of mathematical science.

The spatial extension is infinitely divisible and divided. Nevertheless, the true infinite, strictly speaking, is found only in the Absolute, while space is indefinitely extensive.

According to Leibniz, the moments and the points are not parts of time and space, but only terms. Simple terms referring to things come prior to the sums. The parts are real, defined, and prior in comparison to the whole; but in reference to the ideal entities, such as time and space, unity precedes, and the simple terms follow. The parts are only possible, indistinct, arbitrary divisions, following the whole.

THOUGHTS: By saying terms, I think Leibniz is talking in terms of something like a closure set which terminates / limits the boundaries of some concept. By this way, I think they are carving out a certain piece of the continuum in order to ostense?/refer to it.

Leibniz compared the number with extension and with mathematical bodies. Whereas numbers has no existence without the things measured, the extension and the mathematical bodies are meaningless without entities that act or bear, or without movement. Space, time, and infinity are not real sets; and therefore, we have no positive idea about them. Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time.

Extension is a reduction from the extended, while the extended is a continuum whose parts exist at the same time. The mathematical entities are ideal, as for instance the “shape”, which is never exact and strictly specific in nature. It is not even a universally true and clear quality outside thought. The mathematical entities are modalities, undefined quantities, with which we can access the discrete quantities of the real world.

TOPONDER: I have to understand what the meaning of modality is and how they are located in the spectrum between actual-potential-virtual-real. And how it is connected with the concept of substance and substrate.

** 1.2 The Continuous

In contrast to Newton, who believed that each point-material object coincides with a point of substantial space, Leibniz treated points as extremities or modalities or modes. The location, without doubt, is nothing more than a way of something, like the former or the latter. A mathematical point itself is nothing but a way, namely an extremity. The extension derives from the position but adheres also continuity to the position. Points are positioned in place, but they neither sustain continuity, nor can they stand by themselves.

The ideal, virtual continua are inherent mathematical ideas and they are not composed of parts or points, nor of moments, because the perception of the moment does not contain a sequence. The continuum is everywhere dense, i.e., solid, homogeneous and ceaseless, a plenum, i.e., without breakage of continuity (uninterrupted).

For Leibniz, space is infinitely divisible — in the Aristotelian sense of possibility. Space and time are an order of potentialities. The spatial relationships, although they build up space, are antecedent and parasitic upon space. The Leibnizian space is not the simple sum of the ideal spatial relations but is prior to its parts and divisions.

Thus appears the unrelenting, the completeness of space, which is quondam, as it is not composed of extensional pieces of finite or infinite dimensional areas, separate from each other by two-dimensional boundaries, but is simply divisible, potentially divided. The apparent change and spatial extension are not authentically continuous, because their sequence is terminated. However, there are differences here: the spatial extension is a static representation, it lacks a privileged set of directions and forms a three-dimensional continuum. The apparent change is irreversible and therefore directional; it forms a linear or one-dimensional real continuum.

** 1.3 The Time and the Monad

The Leibnizian theory of time is not articulated with completeness, though it is closely connected with the Monadology. In an earlier letter to Jacob Thomasius, Leibniz wrote that time is nothing else beyond measure of motion. Since each magnitude is a number that consists of parts, why should the definition of time by Aristotle, as a number of change surprise us?

Newton believed that a number of specific events concurrent with one another, they are simultaneous with a certain point in time. According to Leibniz, however, moments constitute only apparent change. A certain phenomenal duration is really dense or actually infinitely divisible, as the physical objects are. Nevertheless, time is uniform or homogeneous; we can divide it an infinite number of times, but it remains prior to its parts, due to the fact that it does not consists of them. It is an idealized entity that refers to the order of succession-relations in the changing phenomena, when we remove the peculiarities of their relata. The truths concerning the time structure are eternal and determine the changing of the phenomena. The fundamental law of being is temporality or succession. An empty space is something we can imagine, but a gap in time incomprehensible. Leibniz wrote to De Volder that time, in contrast to space, is included both in spiritual and in material things, and therefore in perception, the activity of the Monad.

** 2. The Monads

The philosophical stimulation for the writing of Monadology was the problem of the Cartesian mind-body dualism. Leibniz was impressed by the belief that the pineal gland was associated with the communication between cognition and extension, the search for continuity between soul and body. He also sought to quash the naturalistic theory of Locke, who considered space as the common basis of the interaction between mind and matter. Leibniz did not think “that substance is constituted by extension alone, since the concept of extension is incomplete. Nor do I think that extension can be conceived in itself, but I consider it an analyzable and relative concept, for it can be resolved into plurality, continuity, and coexistence or the existence of parts at the one and the same time”.

Leibniz formulated the Monadology gradually by taking the appropriate distances from Cartesianism. Regarding the substance in two of his early works he noted: “1. Substance is being which subsists in itself; 2. Being which subsists in itself is that which has a principle of action within itself (…) no body is to be taken as substance, apart from a concurrent mind (…) Whatever is not substance is accident or appearance …”. In addition he wrote, “I call substance whatever moves or is moved”.

The monad is simple, unified, indivisible, unborn, and imperishable. It is because it has no parts. The monads form compounds, composites, accumulations (aggregata) of simple things. They do not have an extension or form, and they are not visible. However, they are the real elements of natural things. Each unique substance expresses the whole universe in its own way and includes in its concept all events with all their circumstances and all the continuity of external things. The monads are endowed with perception and they are self-reactive. One monad can be distinguished from another by its perceptions, the representation of plurality in the simple, and appetitions, its tendencies, the striving from one perception to another. The nature of the monad is the representation. A monad represents the entire universe, but more distinctly it represents the body that constitutes its entelechy.

The primary feature of the monads, their primary power is perception. Perception is a certain conjunction of the simple with the multiple; it is also the distinction, the identification and the selection, it is the creation and the harmony. The monad as ultimum subsistens is the ultimate basis of all properties and determinations, as ultimum perdurabile is the foundation of any change and as vis activa  itself the source of activity. Pure percpetions concern active states of the active primitive force, in other words the first entelechy which is the soul of living beings. All simple substances or created monads are entelechies of bodies. The composition of the monadic entelechies gives the substantial form to the inorganic world, the principle of impetus. The unclear perceptions relate to potential situations of the passive primitive force (materia prima), derived from the spontaneity of the monad. Apart from the primary forces, there also exist derived ones: by the aggregation of materia prima, secondary matter is being produced, which is governed by active forces as the vis viva, namely the kinetic energy, and the conatus, expressing the potential speed. The second material however is governed by passive forces as well: inertia and antitypia, namely impenetrability, which will be analyzed by the physical theory of Leibniz.

** 2.1 The Immutable World of Monads Is Not in Space-Time

The spatial extension belongs to the domain of phenomena, while the monads are not placed in space; they only represent each other with spatiotemporal characteristics. A representation of a monad of the real world of representational monads is a real condition of the monad, which along with coexisting monads — which are found in suitable corresponding situations — formulate the real world of the monads. A monad beholds the world of phenomena as if it were, in itself, in the center of this vision.

All substances are active. Space and time are produced by the monads and their primary characteristics, their properties. In concert with the principle of perfection and with its equivalent principle of the predetermined harmony, Leibniz concluded that space is a relation inherent in the cross-sectional situations, i.e., the perceptions of monads, whereas the mutual agreement of the monads is such that every perception of a given unit corresponds precisely to a perception of any other unit. The power or activity, and not the extension or passive receptivity, is the deterministic property of the reality.

A possible interpretation of the Leibnizian theory may be closer to the Kantian philosophy: space and time do not exist as completely independent instances or continua, but they make sense only in the subjectively generated contents of the observer’s consciousness. The monad is this energetic observer, who after all lacks any windows; the monad is not located in space. However, it knows the space because it possesses the ability to perceive both the innate, necessary, tautological truths of reason, and the contingent truths of empirical facts.

** 2.2 The Monadic Change and the Mathematical Concept of Series

The Leibnizian philosophy of science is divided into 3 levels, the metaphysical, the conceptual (of the mathematical entities), and the apparent (the bodies). The metaphysical is the level of the mind. The monad or the mind does not accept influences but only affects the body and its representations. The idealizations of space and time are, as we have seen, orders of coexistence or succession. The concept of order originates from the ideal level, while the concepts of succession and coexistence reflect the phenomena. The monads are prerequisites and foundations of the phenomena, they dispose neither a gradual onset, nor a gradual ending, but an abrupt onset and abrupt end. Leibniz describes the monad as a focus of perception, of an anterograde situation that surrounds and represents the multiplicity within unity. The monadic reality is changing entirely, moving from one state another. This real change is a prerequisite for the good consolidation of apparent change. The monadic alteration is not just a virtual thing or an apparent time-like order, but a real time-like order.

“There is, moreover, a definite order in the transition of our perceptions when we pass from one to the other through intervening ones. This order, too, we can call a path. But since it can vary in infinite ways, we must necessarily conceive of one that is most simple, in which the order of proceeding through determinate intermediate states follows from the nature of the thing itself, that is, the intermediate stages are related in the simplest way to both extremes”.

This change in the order of perceptions appears to have a distinct and discontinuous nature: each present state of a substance is a consequence of its previous situation. Clearly, the changes are not truly continuous, there appear interruptions, ruptures of continuity. However, they are characterized by density, because the dense causal connections at the level of phenomena must be correct representations of dense causal connections, with dynamic form. Other times the change is characterized as continuous and flows in conformity with an internal principle. The action of the internal principle that brings about the passage from one perception to another is called appetition.

Two substances are never completely identical to each other: each monad is different from others like a circle is different from an ellipse is different from a parabola. One may consider them as conic sections obtained in accordance with the law of continuity through infinitely small subtle shifts. The essence of the monad is beyond finite analysis and one can access it only through the law of individual series. The procured force is the situation at present, in its trend towards a next state, or the prior implication of the next state. Meanwhile, the primary force exists implying everything that will happen, that is, the nature of the primary active force consists in a law of duration of a progressive series that persists with no obstacle. The procured force is a term of the series, while the active force is the law of the series.

The problems of perception are translatable into terms of geometry, different analysis, perspective, minimum perceptions etc. The complicated and infinitesimal movements of substances are represented by extreme curves of curves, namely by geometric models which mount the vibration of the monad with its maximum and minimum curve. The curve of the maxima is always increasing, and the curve of the minima always decreases. Progression emerges when the increase is greater than the decrease. The order is more fundamental than the disorder, as the real against the phenomenon. It is impossible to find in space the ultimate privileged spot from where one can approach the universal harmony. The sun is privileged and non-privileged from the viewpoint of the fixed stars. In an equivalent way, there is no privileged point of time.

Leibniz proposed a new mathematical model inspired by the theory of the infinite series. However, although aware of the distinction between convergent and divergent series, he did not propose a criterion for their distinction. Anyway, he tended to choose the most perfect series. In terms of combinatorics the “richest” series is one that involves differences and reversals. There is a class of negative or reciprocating type, for the one, the unity: without parts, without form, without division. It does not involve death, initiation, change. There is a progressive class with clearly aggregative characteristics for the multiple: parts, shape, division, dissolution, destruction, beginning, creation, increase, decrease, every form of influence. These reverse features of the one and the multiple are not expressed in accordance with an arbitrary order, but follow the development of two laws, of composition and analysis: they are synthesized by external parts, which directly unfold into the elemental world of geometry and mechanics, attributing the onset of motion in a naturalistic way. The latter two classes are sequences of positive or negative geometrical and mechanical propositions, which order the sum of the terms. They are also sequences of negative or positive propositions of a new set of terms, established by the primary relationship of the analysis of the parts, i.e., of the access of dividing up the indivisible, the atom or the element; of dissolution of heaps of cohesion, resistance, impermeability; of destruction and passing to complexity; and of change, reduction, and attenuation, i.e., intersection of some part of a compound.

** 3. Space, Time, and Motion in the Physical Theory of Leibniz

Descartes believed that the essence of things is the extension which they occupy in space. He reduced all the characteristics of the bodies in modes of extension, supposing that physical changes are movements in space. Leibniz, after 1676, when he turned more clearly against Cartesianism, was confident that the data we observe are limited to material things, their properties, and relations. The Leibnizian Relationalism is based on two key aspects: 1) space-time is not a substance, namely there is no substratum of spatial, temporal, and spatiotemporal points, endowed with spatiotemporal relations ontologically prior to the spatiotemporal relationship between physical objects and events; and 2) the motion is relative, and all spatiotemporal relations are arranged between physical objects and events.

On the contrary, Newton, while accepting that many relationships have no observational consequences, showed that the absolute acceleration of a physical object that rotates is itself observable. To depict the forces generated by the circular motion, he used two mental experiments: the centrifugal forces on the surface of the water in a rotating bucket, and the tension of a string joining two spheres rotating about their center of mass. According to these representations, linear accelerations create observable forces. Newton attributed these absolute accelerations and generated forces to absolute space, which is an unchanging reference system. Therefore, the Newtonian science considered as absolute the differences between state of rest, uniform motion, and accelerated motion. Samuel Clarke, in his renowned correspondence with Leibniz, pinpointed the importance of absolute acceleration.

If the movement of the water in the thought experiment was only relative, yaw forces from the rotation axis would be zero. Leibniz however refused to accept absolute acceleration, although he claimed that we must distinguish between “mere relative change” and “absolute true motions of a body”. Leibniz made this distinction only with respect to the cause of movement: In each movement of two material objects, the body that really moves is the cause of the change in itself.

“For when the immediate cause of the change is in the body, that body is truly in motion; and then the situation of other bodies, with respect to it, will be changed consequently, though the cause of that change be not in them”.

This is not the absolute motion of Newton, but true motion relative to another body. Leibniz characterized the true motion as a subcase of relative motion: the actual motion is relative movement whose cause is the body that really moves. He believed that the centrifugal and centripetal movement are examples of dead forces (potentia mortuus) that are infinitely weaker than the living force. What was, according to Leibniz, real and absolute in motion was the driving force, a tendency to move that consists in vis viva, a real and substantial entity, a fundamental absolute quantity which is inherent in substances.

** 3.1 The Matter, the Body, and the Coincident movementΩ

Newtonian physics was unthinkable without corpuscles. On the contrary, Leibniz rejected the ultimate existence of ultimate, indivisible, firm material particles. Matter is real multiplicity, a cumulative entity consisting of an infinite number of unit.s It is discontinuous and actually infiniitely divided. However, there is no part of space without matter. The matter itself is homogeneous, equally divisible anywhere, and varies with the motion.

To the above premises corresponds the logical consequence that there are no atoms with infinite rigidity. Matter is itself in flux. The body is extended, mobile, and resistant. Each body is simultaneously fluid and solid. Leibniz believed that the solidness or the unity of the bodies originates from the mind, and there are as many minds as vortices, and as many vortices as solid bodies.

The sense is the natural resistance of the boyd against what is trying to divide it; it is a kind of reaction. The human body is a hydraulic-pneumatic machine containing liquids, which act not only through their weight and other mechanisms that are overt to our senses, but also in certain hidden ways as solution, precipitation, congealment, filtration, evaporation, etc. Leibniz distinguished between matter and body. Matter is noting but impenetrability and extension. It is an inert material without spirit, without a principle of activity, and for this reason, without motion. The boyd on the other hand is a combination of matter and an activity principle that may cause motion. Leibniz insisted, in contrast to Descartes, that space and extension are different from the body, because otherwise the motion of the body would not be a real thing. The essence of the body is not to be extended but to move.

Writing to Arnauld, Leibniz insisted that the essence of the body is motion, or a principle of motion, and that extension is unrelated to a principle like this. Therefore, the existence of a body is not subject to spatial or extensional conditions, as there exists “in omni corpore principium intimum incorporeum substantiale a mole distinctum, et hoc illud esse, quod veteres, quod Scholastici substantian dixerint, etsi nequiverint se distincte explicar, multo minus sentantiam suam demonstrate”.

Translation: “in every body the inmost incorporeal substantial principle is distinct from mass, and this is what the ancients, which the Scholastics said was substantial, although they could not explain themselves distinctly, much less demonstrate their opinion.”

Unlike Descartes, Leibniz did not consider immobility as opposed to the motion. Immobility is a special limiting case of motion, as well as equality is a limiting case of inequality. In a digression of his criticism to the epistemology of Locke, Leibniz noted that no substance in the nature is devoid of activity and that “there is never a body without movement, because  — more generally  —  there is never a substance that lackes activity. (…) But I believe that reason also supports this, and that is one of my proofs that there are not atoms  —  because if there were atoms, there could be atoms that underwent no change and were perfectly at rest”

In his Critical Thoughts on the General Part of the principles of Descartes, Leibniz presents interetsing thought experimetns with two cubes, which are perfectly adjacent and then separated, when other bodies collide vertically with one or with both of them (in opposite directions), to show that atomists do not give a sufficient reason neither of the consistency of atomic compounds nor of their dissolution, namely why atoms do not coalesce huge and more than completely indestructible compounds. The primary cause of the indestructible continuum is the movement, specifically coincident movement and the impenetrability. The bodies are solid when their movements coincide. The internal movements are subtle, rapidly unfolding even in solids, as occurs in the winter when “the permanent internal motions of the parts of matter acting in harmony alone predominates in most liquides; hence they harden and sometimes freez solid”.

*** 3.2 The Vacuum

Leibniz claimed that there are no bodies at rest, because otherwise they would not differ from vacuum. If a boyd were at rest, it could not have any cohesion or consistency, because it could be impelled and divided by motion, no materr how small it may be.

“From this there follows a demonstration of the Copernican hypothesis and many other novelties in natural science. The other proposition is that all motion in a plenum is homocentric circular motion and that no rectilinear, spiral, elliptical, oval, or even circular motion around different centers can be understood to exist in the world, unless we admit a vacuum. It is unnecessary to speak of the rest here. I mention these because something follows from them which is useful for my present purpose. From the latter principle it follows that the essence of body does not consist in extenion, that is, in magnitude and figure, because empty space, even though extended, must necessarily be different from body”.

The vacuum remains only a possibility, as in the above inscrutable passage. “Empty space can in no way be distinguished from the perfectly fluid. There is no perfectly fluid body. There is no vacuum” because the actual division of the bodies sprawls out until their ultimate minimum points. Leibniz believed that the same reason that shows that extramundane space is illusory, proves that every empty space is an imaginary thing. To deny the existence of the vacuum, Leibniz juxtaposed with the Newtonian argument (that the fall of bodies in a fluid depends on the specific density of the fluid), the inadequacy of empirical induction. Clarke insisted that the different resistances of mercury and water are produced by their different densities and therefore there is a need for more of a vacuum where there is less resistance. Leibniz would find the chance to correct that different densities depend not so much to the quantity of matter, but on the difficulity of finding space [viscocit], which creates resistance. Furthermore, with regard to the experimental data of Guericke and Torricelli, Leibniz proposed the following counterarguemnt: “glass has small prose which the beams of light, the effluvia of the loadstone, and other very thin fluids may go through”.

Leibniz once wrote that he agreed with Huygens that the concept of empty place and extension alone is the same. He added that “mobility or antitypy themselves cannot be understood from extenison alone but from the subject of extension, by which place is not merely constituted but filled”.

** 3.3 Movement, Vortices, and Energy
From the natural system of the Cartesian philosophy Leibniz rejected, the matter-extension concept, but maintained the principle of plenitude, according to which every extended space should be complete with matter. Descartes had conceived as a fundamental physical principle the law of conservation of the quantity of motion, the absolute constancy of momentum. However, experiments of Galileo and Huygens had shown that the m.v. is not constant: the dynamic proportional measure of the size of an object is not its geometrical dimensions but its mass, while the speed of a body is proportional to the root of the distance it travels. The quantitiy of the fundamental physical conccept of vis via m.v² vaguely describes the conseravtion of energy. Leibniz generalized the principle of conservation of energy as a fundamental metaphysical principle.

The laws of motion depend on the metaphysical principle of equality of cause and effect: if the effect were greater we should have mechanical perpetual motion, while if it were less, we should not have continuous motion. Leibniz alos denied the possibility of generating a state of entropy, considered by Newton in his Optics. There can be no reduction or increase of the amount of energy. He could not accept that in a system, action is generated only with the increase of energy from a lower to a higher level. Moreover, Leibniz accepted Descartes’ view that the motion in an infinite universe, where there is no vacuum, firstly implies an infinite number of vortices, an idea firstly conceived by Leucippus. The space was filled with an ether of ultrafine particles and the rotation of the Sun caused circular motions, vortices, in the ether, which pushed the planets around the Sun ilke boats in a whirlpool.

The question of the gravity was associated with the theory of vortices, supported by Descartes, Huygens, and Leibniz, and the refusal of the latter to accept the action at a distance, because it is not observable. Leibniz considered as the casue of both gravity and planetary attraction the cycloidal motion of ether (de Causa Gravitatis, et Defensio Sententiae Autoris de veris Naturae Legibus contra Cartesianos), a very thin fluid, from traction spokes, which distubs the material in infinite ways, on all sides, with the result however that the movement of planetary bodies converges to a certain direction a in a particular region, wheras the more massive bodies tend towards the center of the vortex. Correspondence between Huygens and Leibniz, which discusses the theory of Newton, throws light on their differences with Newton. The planets do not just move in ellipses, but they also move all at the same level in the same direction around the sun.

Therefore, Leibniz rejected Newtonian attraction, because it could produce movements only in a wider rather than a limited area of three-dimensional space. In another letter, Leibniz wrote prescriptively to Abbe Conti that the most different causes engage with one another in our explanation of gravity and we simultaneously have spherical radiation, magnetic attraction, the dislodgement of spinning material, the inner motion of the fluid, and the circulation of the atmopshere, which all together cooperate to the production of centrifugal and centripetal force. Furthermore, in Tentamen de Motuum Celestium Causis, Leibniz, based on Kepler’s laws, described the fluid orbs that move the planets.

** 4. Arguments

The key features of the Newtonian concept of absolute space and time were, according tot he work of Earman in World Enough and Spacetmme: Absolute versus Relational Theories of Space and Time as follows.

Absolute motion, absolute space, and time are inherent in a substratum of spatial or space-time points. These structures are endogenous (intrinsic) in space and time, unchanged and stable. The mathematical realism of Newton, in terms of space and time, was proven fertile in the field of observation.

By contrast, the arguments of Leibniz are relational. They are based on an armory of principles. At the level of logical necessity there are two self-evident principles: the principle of perfection and the principle of identity. The principles of plenitude and harmony are involved in the principle of perfection; the principle of contradiction is included in the principle of identity. As for the law of sufficient reason, it is based on the perfection of the universe and the possibility of analysis that is presupposed by the principle of identity. At the level of existence, the principles of continuity and individual differentiation (principle of indiscernibles) are derived by the law of perfection. The law of the best possible includes in particular: the principle of maximum and minimum in mathematics, least action or extremum in physics, and the law of the parsimony in the methodology. Furthermore, under certain temporal and spatial conditions, the sufficient reason implies mechanical causality, while identity becomes equivalent in its various forms  —  equality in algebra, congruence and similarity in geometry, equivalence in symbolic logic, and conservation of power, with all its derivative forms, in dynamics.

** 4.1 The Argument about Observability

To make sense with an assertion of the existence of an entity or an attribute of the world, should the presence or absence of that entity or attribute, or a change in such a characteristic, have observational consequences. Let us suppose that space itself exists as a substance. In that case, it makes sense to ask: What is the position of the whole material world in space? How fast does the world, as a whole, move with respect to substantial space? However, only with obseravtion can we determine the spatial relationships between the physical objects, the movements of material objects, positioning with respect to one another, etc. There are no available observations for an understandable identification of the position of the world as a whole in the substantial space, nor of its speed in reference to the substantial space, etc. Therefore, it becomes clear that such claims do not make sense according to the principle of verification and there can be no substantial space.

Here is a Leibnizian version of the argument:
“Motion does not indeed depend upon being observed; but it does depend upon being possible to be observed. There is no motion, when there is no change that can be observed. And when there is no change that can be observed, there is no change at all”.

** 4.2 The Principle of Indiscernibles

“To suppose two things indiscernible, is to suppose the same thing under two names”.

“Space is something absolutely uniform; and without the things that are placed in it, a point in space does not differe in any respect whatsoever from another point in space”.

The arguments based on the principle of indiscernibles usually take the following form: Suppose we have the possible worlds A and B, such that they are identical to each qualitatative attribute. Then A is the same possible world as B.

In his correspondence with Clarke, Leibniz used two similar arguments. Firstly, imagine a second universe like ours, except that all matter is shifted and placed in another location in the absolute space, without any change in the relationship between objects. If the space is Euclidean both places are exactly the same, so there would be no observable differences. Secondly, imagine a universe just like ours, except that the absolute speed of each piece of material varies and differs in an unchanging, fixed amount, without any change in the relationship of one object to another. Since the two speeds differ only by an amount that remains constant, no observable differences will be reported. The two universes are not distinguishable. If there were absolute space, the particles would have completely different motions, therefore the supposition of an absolute space is contradictory to the principle of indiscernibles. The absolute space and absolute space-time are not observable, and they give birth to indistiguishable situations. The principle of indiscernibles is based non the principle of sufficient reason.

** 4.3 The Principle of Sufficient Reason

Suppose that a theory allows us to distinguish between two different states of the world, A and B. Nevertheless, it is impossible in principle to discover the causal reason: why A should be real, instead of B, or vice versa, Then the theory must be rejected.
“… if space was an absolute being, there would something happen for which it would be impossible there should be a sufficient raeson”

The principle of sufficient reason declares that everything that exists in a state of affairs s, exists for an integrated reason, which (1) constitutes the necessary and sufficient condition for s; (2) shows clearly and precisely why it takes place s instead of another; (3) provides, when possible, a full description, a complete explanation of s; and (4) does not require another reason of the same type.

** 4.4 The Principle of Plenitude

The universe is plenteous, everything is a plenum, and all matter is interlinked, so that each movement can have effects even on the most remote bodies and each body is influenced by the mobdies with which it comes into contact, and also by those who come into contact with the latter, and so on.

Clarke had the impression that, with the principle of plenitude Leibniz identifies space with matter. The latter, convinced that absolute space and absolute space are only a representation of relations, replied in compliance with the principle of plenitude:

 “I don’t say that matter and space are the same thing. I only say, there is no space, where there is no matter; and that space in itself is not an absolute reality. Space and matter differ, as time and motion. However, these things, though different, are inseparable.”

“But yet it does not at all follow that matter is eternal and necessary; unless we suppose space to be eternal and necessary; a supposition ill grounded in all respects”.

** 4.5 The Principle of Continuity

How a continuum can be constucted of discrete points? The source of the difficulties with composition of the continuous lies in the fact that we grasp matter and time as substances. The Leibnizian gateway from the labyrinth of the composition of the continous is to view the world of the continuously extended matter as secondary and derivative.

In 1687, Leibniz produced the principle of continuity by considering the concept of infinity in geometry. Later, he solved the problem by considering real but strictly individual dynamic centers, whose qualitative, causal, gradual interaction generates mechanical interactions at the level of phenomena and consequently apparent changes ariculated in the virtual continua of space and time.

The mechanistic philosophers of the seventeenth century denounced active principles. With the principle of inertia alone, they explained every motion of matter. Leibniz criticized Descartes focusing on his failure to see that motion must be established with energy. At the same time, the Enlightenment movement supported a European and global international cooperation and Gottfried Wilhelm Leibniz had correspondents ranging from London to Beijing.

** 5. Conclusions

The spatial temporal structures of the Newtonian theory are intrinsic, inherent in a substratum of spatiotemporal points, while in the ideal space-time of Leibniz the relations are external (extrinsic) to space and time. Relations are interface determinations completely independent of the possible phenomenal relata, while the structures of absolute space and time are unchanged and stable.

The Leibnizian arguments do not always appear convincing. In fact, with his argument of a world where the West would take the place of the East, Leibniz tries to combine the principle of sufficient reason with the principle of indiscernibles, in an obscuring manner, when asking for the sufficient reason of the displacement, while probably begging the question. The argument would seem invalid according to logic, because Leibniz asks “why every thing was not placed the quite contrary way, for instance, by changing East into West,” eliminating a required premise that should describe the coordinates of East and West. In another argument again, when assuming that we change the position of the world within space, Leibniz maintains as immutable the internal spatial relationships of physical objects, one in relation to the other, which seems contradictory to the very own Leibnizian belief that there is no body that does not move. However, one should consider the strongest argument of Leibniz, based on the infiniteness of the world. In comparison with the infinite, any displacement may be insignificant.

A powerful argument against the Leibnizian relationism is developed in N. L. Wilson’s Individual Identity, Space, and Time, in the Leibniz Clarke Correspondence:

Important complications emerge if we introduce coordinate systems in space and time. Places and dates acquire now internal relations which should stay untouched by any permutation. The introduction of inertial temporal and spatial coordinates is embedded within an empirical rationalism that encounters space, time, and space-time dimensions in a non-relational manner. Furthermore, the various possible worlds are not different names for the same subject: they are distinguishable. Another Leibnizian argument referred to time: if the world were created a few million years eariler, it would be indistinguishable from this one here, since “the beginning, whenever it was, is always the same thing”. There is a confusion around the dubious principle of indiscernibles: if two objects x and y are exactly alike, they are also numerically identical, regardless of the permanent or contiguous character of their similarity. Genuinely logical, however, is only the principle of the indiscernibility of the identicals: if k and l are numerically identical, that is, they are simply different names for the same object, then k and l are exactly alike.

Clarke emphasized he issue of inertial phenomena, referring to the example of Galileo with the ship. The movement of the ship is really a different situation with truly different effects even though they may be beyond our perception. A sudden stop of the ship would bring about other more tangible effects. Clarke noted that the argument about Newton’s absolute motion is mathematical and that it demonstrates according to real effects the absolute motion, therefore cannot be answered by simply asserting the opposite. The space and the time are not only an order of things; they are real quantities. Mathematization established the actual inertial motion, as described by Newton, as an indispensable concept for a consistent physics.

Of special significance was Leibniz’s counterargument againts the mathematical argument of Newton regarding absolute acceleration: Leibniz supported that the Absolute is the inherent in the body force or motive power, the vis viva. This interpretation was an overt subterfuge, in conflict with the first law of Newtonian mechanics, the law of inertia, which explains that a point mass either moves linearly and smoothly or remains at rest, unless acted uupon the influence of external forces or when the forces affecting are cancelled out. Lebiniz’s objection was based on the following distinction: that the vis viva refers only to impacts, while the observed pendulum movement, the rotation, and the orbits are manifestations of the dead force m.dv), infinitely smaller than the vital force.

Nevertheless, Newton clarified the absolute motion with his first law. Absolute motion is created or modified only by the impact of force to the (moving) body, and it changes with any impact of force upon it, while the relative movement can be changed or created, without the influence of force on the relatively moving body, and it is not necessary to change with every impact of force upon it. The principle of inertia is an empirical principle, manifested as: (1) inertia of a body that remains in rest, insofar it is not influenced, but also by the impact of forces, as an escape from rest either with distractions or with resistance or gradually; and (2) as the inertia of a body that moves linearly and smoothly, insofar it is not influenced, but also as a change of direction, or an acceleration or deceleration under the impact of forces.

We conclude that the two thought experiments and the arguments of Newton intended to establishe the absolute circular motion and the absolute acceleration during rotation, and they are connected to the second law of conservation of momentum, and, indeed, of the angular momentum. According to this law, the angular momentum of a partice or the main torque of an inertial system is modified only be the influence of external forces, whereas internal forces can only change the torgque of parts of the system and the angular velocity. Newton concentrated his attention on the issue of absoluet acceleration during rotation, because a simple variation of the angular speed, can be, according to the second law, the effect of internal forces. The absolute acceleration, however, may increase the moment of inertia, the ngular momentum of the sytsem overall. In modern parlance, the dimensionalitiy of angular velocit is T⁻¹, and the one of angular acceleration T⁻².

Leibnize tended to pinpoint an explanation originated with Huygens, who referred tot he cycloidal motion of ether that disturbs the matter in countless ways, from all sides, in order to address in a somewhat limited way, the inertia as resistance, absolute due to the viscosity of the fluid ive due to its density. With such claims, he derived the conclusion that every motion is either rectilinear or is reduced to a synthesis of rectilinear movements. The accelerated motion, either curved or rectilinear, was represented by Leibniz with polygonal infinitesimals as a series of smooth rectilinear motions interrupted by impulses of dead force. Newton, however, represented the accelerated motion with a continuous curve and the forces and acceleration involved are finite and not infinitesimal.

** From Relationism to Relativity

The concept of Leibnizian space came prior to that of spatial relations, but it was not an absolute framework of measurement. A position in space was determined only in relation to another position, as far as the latter could be regarded as fixed. That is exactly what led Anapolitanos to evaluate the theory of Leibniz not only as relationist, but also as relativistic theory, since one of the basic postulates of the special theory of relativity is that there is no preferential spatial system of reference. Leibniz however remained attached to metaphysical notions such as that of the mind, as the cause of motion. The dominant scientific theory, until the appearance of the theory of relativity, was that space and time were absolute reference systems of things, objects, and events. The argumentation of Leibniz questioned the verifiability of absolute space because in any system of coordinates with relatively uniform motion we have not a means to distinguish the absolute uniform motion. “How would the world be, if there was a reportable unobservable change?” “The same” , would Leibniz reply. The Newtonian, however, might support the following: it is not true that in any possible world, observability, i.e., observational conditions, disprove the existence of real space.

Nevertheless, in the special theory of relativity, we still have an absolute motion, in terms of a class of highly abstract and unobservable entities. The speed of light is always the same in all systems of coordinates, whether or not the light source is moving, and with any way it may move. How does the speed of light remain constant in two coordinate systems that are in relative uniform motion? This has to do with the relativity of time introduced by the Lorentz transformations.

The contribution of Leibniz in theoretical physics of space and time was operative, though not prescriptive. The emphasis on the concept of relation has contributed indirectly to the discovery of the main results of the theory of relativity, according to the Lorentz transformations: the relativity of simultaneity, the time dilation, and the length contraction of the bodies. The special theory of relativity accepts the fixedness of relations only for systems of coordinates that move with relative uniform motion: the time is determined by clocks, the spatial coordinates by set of rods, and the movement may affect clocks and rods, as shown by the effects of the electromagnetic field; events that in a reference system coincide or occur at the same point in space, in other inertial system can occur at different times or in different places in space, while the deletion of points of the space-time manifold is used by relativists to construct cosmological models.

The motivation of Einstein, when he formulated the general theory of relativity, was , besides the problem of gravity, a thought experiment to eliminate the absolute motion. However, he only revised the concept of absolute space,w hich was replaced by the concept of the displacement field, which is a component of the total field. The structures yet are endogenous, the metric of space is a function of the distribution of matter and energy, and the laws of physics are accepted in every system of reference.

The relativity of motion presupposes variable structures, frames of reference of the Riemannian geometry. The acceleration here is a result of the curvature of space-time, which produces dramatic changes in the observable gravitational effects. The equivalence of all spatial points, i.e., the homogeneity of space, the isotropy, i.e., the equivalence of all space directions, and the homogeneity of the time, in the light of Leibniz’s saying that a point in space does not differ in any respect whatsoever than any other, seem to conform to relationalism, but in fact, the principles of the general theory are realistic propositions. They apply exactly to the absolute space-time and approximately to real systems, while the validity of the general theory is not limited to inertial systems.


* [[https://scholar.harvard.edu/files/mcdonough/files/causality_and_preestablished_harmony_penultimate_draft_in_english.pdf][Leibniz on Pre-established Harmony and Causality]]
Jeffrey K. McDonough

There are two realms: one of bodies and efficient causation, one of minds and final causation.

** A Pre-established Harmony: Bodies and Minds

How is it that our minds and bodies can causally effect each other? Leibniz’s novel solution to this mind-body problem is that they can’. The interaction between our minds and bodies that seems so obvious to us is, in reality, an illusion, although “well-founded.”

At just the moment that one forms an intention to move their leg, their leg moves of its own accord. At just the moment that the ball collides with one’s hand, the mind independently comes to experience pain. Leibniz suggests taht mind and body are like two causally independent but synchronized clocks: the appearance of causal interaction between them is an illusion founded on a harmony pre-established by God.

Leibniz’s theory of pre-established harmony feels a bit like Indra’s Pearls where every mind has mutual perception and the whole consists of such mutual perceptions. Drawing on theoretical considerations, Leibniz insists that each mind perceives everything that happens in its world, that is not only in its immediate vicinity, but also across the city, on the other side of the earth, and indeed, on the other side of the universe.

Every body is connected and when a change happens in any body anywhere, a corresponding change occurs in a mind. When a change happens in any mind with a corresponding change in its body, ripple-effects occur in every other existing body.

Leibniz’s theory of pre-established harmony thus ultimately demands not merely the divine coordination of particular mind-body pairs, but even more boldly the divine coordination of each mind with all existing bodies and each body with all existing minds.

Leibniz defends his theory of pre-established harmony by highlighting that it helps to reconcile the metaphysics of Aristotelian-Scholasticism with mechanistic science. Leibniz also, I feel arrived at this theory by examining each of the existing alternatives of the time.

An alternative theory is the theory of physical influx. It posits, as Leibniz understands it, that minds and bodies causalyl interact when something – some form of being — passes from one substance to the other. Although they were often vague on this point, Leibniz’s suggestion that it is baseless.

Definition of this concept from Francisco Suárez, 17th century Scholastic, as per McDonough suggests that genuine causation occurs when a cause transfers some form of being to its effect. It implies that the foot causes the soccer ball to move by transferring something to the soccer ball — perhaps motion or energy — and that a picture of, say, Pelé causes the mental representation of Pelé by transferring something of Pelé image or likeness, first to a medium, then to the sensory organs, and ultimately to the mind.

Leibniz rejects the theory of physical influx as a general theory of causation because he thinks it is simply inconceivable that anything can be transferred from one substance to another.

Leibniz famously argued that monads are windowless: they don’t have any openings to enter through or go out of. If that is taken as axiomatic, then clearly causal interacitons between minds and bodies (or minds and minds) cannot be understood in terms of the theory of physical influx. For if nothing can go in or out of minds, hen they can neither receive from, no impart to, anything, including forms of being, as the theory of physical influx demands.

A second alternative to Leibniz’s theory of pre-established harmony is the theory of occasionalism. The theory had already enjoyed a long history before Leibniz’s time. It found new impetus, however, in suggestive remarks made by Descartes and was developed in vairous ways by second generation Cartesians such as Géraude de Cordemoy, Louis de la Forge, Arnold Geulincx, Johannes Clauberg, and above all, Nicholas Malebranche. The central idea of occasionalism is that God is the only genuine, efficacious cause in the world. Creatures lack any causal efficacy of their own and serve merely as occasions for God’s direct causal intervention.

Although, not popular today, the theory of occasionalism attracted a considerable following in Leibniz’s era and was supported by a raft of formidable arguments some of which continue to motivate some contemporary views on causation.

Leibniz rejects occasionalism for a variety of reasons. According to Leibniz, it is essential to created substances to be loci of causal activity. To suppose that creatures enjoy no causal efficacy of their own would be to reduce them to mere models of God. To Leibniz’s way of thinking, occasionalism thus collapses into the doctrines of Spinoza. Another line of argument draws on Leibniz’s understanding of God’s perfection. Leibniz maintains that his theory of pre-established harmony, according to which Godś design is so perfect that it requires no subsequent corrective intervention, is more suitable to God’s perfection than it is the theory of occasionalism, which would require God to constantly tinker with his creation.

In presenting his theory of pre-established harmony, Leibniz often speaks of there being two realms, a realm of bodies and efficient causation on the one hand, and a realm of souls and final causation on the other.

Material world is affected by efficient causes, whereas the world of souls are affected by the law of appetites or the final causes.

Minds unfold teleologically, that is, they act for the sake of ends. Bodies unfold efficiently, that is, they are driven along by efficient causes in accordance with the laws of nature.

** Causation in the Realm of Bodies

Leibniz contributed to formulating and refining laws of motion. He criticized Descartes’ laws of collision. He vigorously defends a series of conservation laws, including, most faously, the conservation of vis viva. Leibniz seeks to clarify what he sees as the philosophical implications of the laws of nature, defending, in particular, three central theses.

The first thesis concerns modal status of the laws of nature. Are laws such as Galileo’s law of falling bodies necessary or contingent? Descartes’s hugely influential treatement of the laws of motion implied to many that the laws of nature must be necessary — a view defended explicitly half-generation later by Spinoza. One such a view, the laws must be as they are. Galileo’s law of falling bodies could no more fail to hold tahn could the laws of geometry or arithmetic. Another view, attributed by Leibniz to Bayle, and dominant today, is that the laws of nature are contingent and arbitrary. On such a view, Galileo’s law just happens to be true. The world could have been different with respect to falling bodies: instead of falling with constant acceleration, bodies might have fallen with constant velocity or variable acceleration. Furthermore, on this view, there is no decisive reason in favour of Galileo’s law. If we imagine that God has created the world, we may imagine him as being indifferent, or at least not set upon, creating the world in accordance with Galileo’s law.

Leibniz opposes both of these extreme views. He maintains that the law of nature as neither necessary nor arbitrary. Rather they are contingent but nonetheless determined by considerations of optimality.

Leibniz effectively suggests that both Descartes and Bayle are wrong. Descartes is wrong because there is a sense in which the laws of nature are contingent. If we abstarct from God’s goodness, we can imagine God’s creating the world with different laws. In this respect, the laws of nature are not like the laws of arithmetic and geometry. But Bayle  —  at least as Leibniz interprets him  — is also wrong. Although the laws of nature are contingent, they are not arbitrary. God, according to Leibniz, has chosen to instantiate the actual laws of nature not out of whim or fancy, but because they are essential to the best of all possible worlds.

Leibniz’s second thesis concerns with what we might think of as the metaphysics of the laws of natrue. What are the laws of nature and how do they govern the world? Talk of the laws of nature, their creation, their discovery, etc. can encourage the thought that laws of nature are thing-like, that they are independent ingredients in the world on a par with mind and bodies. But that cannot be Leibniz’s picture. Leibniz’s fundamental ontology of the created world is exhausted by substances: true unities modeled on minds or organisims. Not being true unities — being nothing like minds or organisms  —  laws of nature cannot be counted among the fundamental ingredients of the created world. Rather, for Leibniz, they must be identified with concepts or abstractions enjoyed by rational minds and applicable to events in the world. Galileo’s law of falling bodies is not a thing but rather a pattern, a regularity or rule understood by God and other intelligent minds. With the laws of nature so understood, it is also immediately clear that, for Leibniz, the laws of nature cannot govern bodies by, say, pushing or pulling them around. Instead, Leibniz maintains that bodies are determined in their behaviour by forces within bodies themselves. Heavy bodies near the surface of the earth fall with a constant acceleration not because the laws of nature push or pull them, but rather because they have been endowed with intrinsic powers that direct them to fall with constant acceleration. For Leibniz, laws of nature are explanatorily powerful insofar as they allow us to subsume particular phenomena under general regularities, but they are not causally powerful in the sense that they directly bring about the behaviours they subsume.

Malebranche identifies the laws of nature with divine decrees. But how are those decrees supposed to regulate the behaviour of bodies?  Leibniz argues that if the laws of nature are identified with general decrees made at the beginning of creation, but not grounded in the intrinsic powers of bodies, then they cannot now be effective as there needs to be a force that still subsists with them. But might not the laws of nature be identified with general decrees and their efficacy nonetheless be grounded in God’s particular volitions, volitions made in accordance with those general decrees? Leibniz thinks this would be no better. For he insists that miracles occur when something happens that passes the forces of creatures (?) as would happen for example, if water were to burn or pigs were to fly. Given such an understanding of miracles, Leibniz argues that if the efficacy of the laws of nature were grounded in God’s particular volitions, then God would be committed to incessantly peforming miracles. Seeing such activity as being unworthy of God’s wisdom, Leibniz concludes that occasionalists fail to offer a tenable view of the nature and efficacy of the laws of nature.

Leibniz’s third central thesis concerns the role of teleological explanations in the natural science. Descartes and Spinoza made no appeals to final causes in physics. Spinoza seemed to go a step further in suggesting that teleological explanations get the order of explanation the wrong way around and the final causes are “nothing but human fictions”. While acknowledging the limits of earlier scholastic explanations, Leibniz nonetheless argues that a wholesale rejection of teleological explanation is neither necessary nor prudent. Like many proponents of the new science, Leibniz is happy to grant that we cannot hope to know all of God’s ends, but he sees no reason to suppose that we cannot discern some of them.

Leibniz’s work on the laws of optics provides him with another, less obvious, route for defending teleological explanations. Aroundd the late 1670’s, Leibniz came to see that the law of reflection could be derived from a principle acccording to which, as he puts it, “nature, proposing some end to itself, chooses the optimal means”.

By the early 1680s, Leibniz was able to provide a unified account of the two central laws of geometrical optics — the law of reflection and the law of refraction — by showing how both follow from the principle that light always travels along “easiest paths,” where easiest paths are rigorously defined in terms of distance and the resistances of the relevant medium. Leibniz continued to develop his approach to the laws of optics over the decades that followed, showing, for example, in his Tentamen Anagogicum of 1696 how optimal paths could also be determined in more difficult cases involving concave and convex mirrors. In a series of pioneering studies, Leibniz showed how similar reasoning could also be applied to solve specific problems in mechanics. The techniques that Leibniz pioneered in his optical and mechanical studies proved to be precursor to what are now known as variational principles.

Leibniz suggests that what we may call his “optimality principles” support teleological explanations within the natural world in two rather different ways. First, Leibniz thinks that optimality principles — like elegant laws of motion and simple conservation principles — support teleological arguments from design.

** 3. Causation in the Realm of Minds

Leibniz in his most mature period thinks that the causal activity of creatures is ultimately grounded not in bodies but in monads alone.

Monads contain both perceptions and appetites. In virtue of their perceptions, monads perceive the world around them. Indeed, Leibniz maintains that in virtue of their perceptions, each monad perceives, from its own point of view, consciously or unconsciously, everything that has, is, or will happen in its world.

And you, of course, do something similar from your own distinct ponit of view. In virtue of their appetites, monads transition from one perceptual state to the next.

Leibniz distinguished between three kinds of monads on the basis of their representational capacities. The lowest kind of monads are called bare monads. These have perceptions that are typically highly confused. The souls of plants serve as paradigms of bare monads. Monads on the intermediate level called sensitive monads have not only confused perceptions but also the ability to be consciously aware of distinct entities as distinct entities. The souls of animals serve as paradigms of sensitive monads. The highest kind of monad — what Leibniz calls minds — have perceptions that provvide them with higher-order thoughts — the ability to reflect on their own perceptions andd themselves. Leibniz maintains that because the yenjoy higher-order thoughts, mindds are capable of grapsing necessary truths concerning morality, mathematics, and metaphysics.

It is clear from Leibniz’s theory fo pre-established harmony that monads are supposed to unfold teleologically. It is less clear how we should understand the teleological unfolding of monads in cases of on-willful, non-voluntary action. In a note in his Dictionaire histonque et critique, Pierre Bayle famously raises just such a case. Bayle notes that according to Leibniz’s theory of pre-established harmony there is a sense in which a “dog’s soul would feel hunger anddthirst at certain times even if there were no bodies in the universe”. Bayle objects to Leibniz’s position by saying that he cannot understand how a dog’s soul can spontaneously change.
TODO: I have to read further to understand what objections Bayle raises exactly.

There is a general concern in that suppose we grant that we can understand how monads might unfold teleologically in cases involving willful, voluntary actions. We might still wonder if we can really understand how monads can unfold teleologically in cases where their successive representaitonal states are not willful or voluntary, either because they are not perceived as being good, as seems to be the case with Bayle’s dog, or because they are not consciously perceived at all, as will always be the case for bare monads (and for higher monads as well much of the time).

Leibniz’s thought in a letter to Sophie Charlotte suggests that although the behaviour of bare monads cannot be exactly like the behaviour of minds, nonetheless our experience of our own minds gives us our best and only grip on what it is like to be a bare monad.

When the dog is struck by a stick it transitions to perceptions of pain. But it is not driven to those painful perceptions by willful, voluntary appetites. Nonetheless it must be driven to those perceptions by some appetite — as we have seen, Leibniz insists that each monad is causally isolated from both bodies and dother monads. So, according o this lines of response, monads must be endowed not only with willful, voluntary appetites, but also with non-willful, non-voluntary appetites, appetites that are not guided by monad’s own perceptions of the good. Although there is little textual evidence that Leibniz means to countenance appetites not govered by a monad’s own perception of the good, this proposal at the least offers an intuitivev solution to Bayle’s objection. It allows us to suppose the Bayle’s unfortunate drog is driven from its pleasant perceptual state to its unpleasant perceptual state primarily by non-willful, non-voluntary appetites. The postulation of more than one kind of appetite thus offers a relatively straightforward replacement within Leibniz’s system for the causal influences that we would normally attribute to external causes.

That monads unfold teleologically does not, for Leibniz, preclude their unfoldign efficiently. And, indeed, there are good reasons to suppose that Leibniz thinks that monads do also unfold efficiently. He describes monads as being driven along by their perceptions and appetites according to their laws of the series. Leibniz’s efficient causal story is complicated somewhat by his support of the traditional theological doctrines of divine conservation andd diveine concurrence.

It is likely that Leibniz believes just as his scholastic predecessors believed, that he could reconcile such traditional theses with a commitment to genuinely creaturely causation.

Leibniz’s famous pre-established harmony between minds and bodies is thus underpinned by a pair of less widely recognized causal harmonies, one within the realm of bodies, one within the realm of minds.

** [[https://www.researchgate.net/profile/George-Gale-2/publication/262278420_The_role_of_Leibniz_and_Haldane_in_Wiener%27s_cybernetics/links/57dfe4ad08ae484409238ffd/The-role-of-Leibniz-and-Haldane-in-Wieners-cybernetics.pdf][The Role of Leibniz and Haldane in Weiner’s Cybernetics]]

George Gale

1997

16 pages

** [[https://www.researchgate.net/profile/George-Gale-2/publication/265310162_Leibniz_and_some_aspects_of_field_dynamics/links/5bfc1a15458515b41d0f7260/Leibniz-and-some-aspects-of-field-dynamics.pdf?origin=publication_detail][Leibniz and Some Aspects of Field Dynamics]]

Leibniz and the link between Boscovich.

Conservation Theory vs. Atomistic Theory

Dualist vs. non-dualist conception of matter and force
Newton is said to be a dualist while Leibniz/Kant/Boscovich is non-dualist. Faraday is said to be difficult to classify but ultimately seems to belong to non-dualist.

Three features of Leibniz’ conception of field theory:

1) They are ant-corpuscularian and continuistic; hence thy are opposed to the discrete view of matter and opposed to action-at-a-distance
2) Dynamical in the sense of offering an interpretation of phenomena which is grounded in forces, rather than grounded in matter-as-pure-corporeal-extension
3) Non-dualistic, that is, they do not lend themselves to a twocategory, matter anhd force, account of phenomena

II. Characteristic of Leibniz’ Ontology of Forces

Three levels of Leibniz’ Ontology:

Primary Level
Monads

Corporeal Level
Primitive Active Force ~ Aristotelian form
Primitive Passive Force ~ Aristotelian matter

Not physical but inferential referents that lie at the limit of observation

Extension is an observable but not a simple property of corporeal substances as it is further analyzable. It depends ultimately upon force, the tendency of things to act. The corporeal substance is not an entity which exhibits two equally primitive properties i.e. extensional properties and force properties. Rather extension is the derived property. It is the phenomenal manifestation of the activity of the underlying and fundamental forcething.

Leibniz attacked the Cartesian position that mv was a conserved quantity and instead along with Huygens proposed the quantitive ½mv² as the conserved quantity.

Body Level

Leibniz posits that if two atoms as undividable units are held together, the glue that holds them together will present the problem of an infinite regress where further atoms may be found.

The paper closes by detailing some of the complex interrelationships between the field theory of Boschovich and the precursor ideas in Leibniz.

** [[http://mally.stanford.edu/leibniz.pdf][A (Leibnizian) Theory of Concepts]]

Concept Summation, Concept inclusion, Complete individual concepts, possible worlds, and the containment theory of truth

This work depends on the axiomatic theory of objects developed in:

Abstract Objects: An Introduction to Axiomatic Metaphysics — 1983
Intensional Logic and Metaphysics of Intensionality — 1988a
25 Basic Theorems in Situation and World Theory — 1993
Natural Numbers and Natural Cardinals as Abstract Objects: A Partial Reconstruction of Frege’s Grundgesetze in Object Theory — 1999

Developed on two strands of Leibniz’ work:
His work on the theory of concepts
His work on (modal) metaphysics of individual concepts

Fundamental theorem of his metaphysics of concepts:

if an object x has F but might not have had F, then:
i) the individual concept of x contains the concept F
ii) there is a individual concept y (a counterpart of the concept of x) which doesn’t contain theh concept F and which appears at some othehr possible world.

In working towards this goal, neither ‘possible world semantics’ nor set theory is used, but the goal is to build an axiomatized realm of abstract objects which have well-defined, and anteceddently-specified, existence and identity conditions.

The containment theory of truth will be defined so that:
a) it applies both to the logic and modal metaphysics of concepts
b) it is consistent with the existence of contingent facts

** Works on Concepts that doesn’t refer to Leibniz oeuvre
- Quality and Concept — G. Bealer (1983)
- A Theory of Concpts and Concept Posession — G. Bealer (1998)
- The Metaphysics of Concepts — C. Peacocke (1991)

** Works on concepts that develop Leibniz’s theory of concepts
- Leibniz’s Interpretation of His Logiacl Calculi — Rescher (1954)
— Einführung in die Theorie der Begriffsysteme — Kauppi (1960)
— Über die Leibnizche Logick — Kauppi (1967)
— Leibniz’s Complete Propositional Logic — Castañeda (1976)
— Leibniz’s Syllogistico-Propositional Calculus — Castañeda (1990)
- Leibniz’s Calculus of Real Addition — Swoyer (1994)
- Leibniz on Intension and Extension — Swoyer (1995)

** Those that treat the modal metaphysics but doesn’t address the theory of concepts
- Leibniz on Possible Worlds — Mates (1968)
- Reference, Essentialism, and Modality in Leibniz’s Metaphysics — Mondadori (1973)
- Analyticity and Necessity in Leibniz — G. Fitch (1979)

§ 1: Concepts, Properties, and Concept of Properties

The concept F contains the concept G iff concept F is identical with the sum of the concept F and the concept G.

Swoyer designates this principle ’Leibniz’ Equivalence’.

A) F ≥ G ≡ F = F ⊕ G

* [[https://www.jstor.org/stable/40971103][Aristotle, The Scale of Nature, and Modern Attitudes to Animals]]

The article starts out by detailing how Aristotle’s ideas differed from that of Plato’s.

A brief description of Plato’s hierarchy is given and it is described how it is a dichotomous division until ultimate species are reached which is thought to be a system opposite to Linnaeus.

TODO: I have to understand how Plato’s system is binary and how Linnaeus system is binary. I think Plato‘s is literally a binary tree in its semantics, whereas, Linnaeus binary tree is only binary in its syntax where genus and species names are combined into one name but the referrents could have a less strict graph structure underneath describing the containments.


Principle of Plenitude and Great Chain of Being are described to work in harmony to produce variety. A curious aspect outlined is how the idea of plenitude was opposed to the idea of extinction because since there was a dictum like nature to the idea that the variety in the world always increases.

TODO: How exactly was the Scale of Nature refined by the medieval theologians?

Five properties of categorization are mentioned: Genus / Species / Differentia / Property / Accident

I think it formally begins from substance / accident higher up.

Genus: Part of essence. Some attribute in common to all.
Species: Group of things similar in essence
Differentia: What distinguishes species among each other
Property: Attribute shared by all members of a species, that is not part of essence and not necessary to distinguish it.
Accident: Attribute shared by some members and not part of its essence.

TODO: I think it requires further look from my end on how exactly these interplay to create a hierarchy.

There is also the idea of a sort. I think this relates to many sorted logic.

5 predicables and this finally evolving into Linnaeus system is outlined.

Internal finality is shown to be an idea which lead to a discrete classification in the essay, but I felt that this part was not elucidated properly in a way that makes legible on how exactly this leads to a discrete classification.

After the part of covering history, the author goes on a tirade saying how animals being treated today have been influenced by these philosophical viewpoints. While this critique is well intended and heartfelt, keeping it to the end of the essay made it a bit of abrupt and stand out from the movement of the rest of the essay. I think by melding the arguments throughout the essay from the beginning, and then slowly working up to the conclusion rather than putting it as a separate section would have added to the mettle of the argument and made it far more forceful. Right now, as it stands, it is a bit of a social commentary that is adjoined in a non-concordant fashion to a historical review of Aristotelian classification.

** Next Reads

The Physical Theory of Leibniz - George Gale

Did Leibniz Have a Practical Philosophy of Science; or, Does ‘Least-work’ Work? - George Gale

Physics and Metaphysics in Newton, Leibniz, and Clarke - M. R. Perl
